### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by ajotcham** [tmweigand/membranes#7]
- [ ] - Start setting up different length domain for rectangle, change math
  - [x] - Polymerization
  - [x] - Equilibration
  - [ ] - Hydration
  - [ ] - Permeation
- [ ] - Setup easy file management on Bridges Including Restarts
   - [ ] - Polymerization
   - [ ] - Equilibration
   - [ ] - Hydration
   - [ ] - Permeation
- [ ] - Submit on Bridges
  - [ ] - Polymerization
  - [ ] - Equilibration
  - [ ] - Hydration
  - [ ] - Permeation

**Comment by tmweigand** [comment]
@ajotcham Can we make sure we use a different random seed on the submit scripts. Maybe you set it as the slurm job id? That should be random enough for our purposes.
